default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("db_username") { 5 } %>
  password: <%= ENV.fetch("db_password") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: so_postgresql
  
test:
  <<: *default
  database: so_test

production:
  <<: *default
  database: so_prod
  